package DBHelper;

//Required imports
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;

/**
 * Helper class for database connectivity
 * Code generated by SQL Helper
 */
public class DBHelper {

	/**
	 * Static value to store the database path and name
	 */
	private final String DATABASE_NAME = "C:\\Users\\smfpr\\OneDrive\\Documents\\School\\2025\\Spring\\COP3330\\Module 7\\Module7\\db\\University.db";

	/**
	 * The connection object used to connect to the database
	 */
	private Connection connection;

	/**
	 * The statement object used to execute statements
	 */
	private Statement statement;

	/**
	 * The result set returned from a query
	 */
	private ResultSet resultSet;


	/**
	 * Constructor
	 * Clears connection, statement, and resultSet
	 */
	public DBHelper() {
		connection = null;
		statement = null;
		resultSet = null;
	}

	/**
	 * Creates a new connection to the database and a new statement object
	 */
	private void connect() {
		try {
			Class.forName("org.sqlite.JDBC");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		try {
			connection = DriverManager.getConnection("jdbc:sqlite:" + DATABASE_NAME);
			statement = connection.createStatement();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Closes the connection, statement, and resultSet
	 */
	private void close() {
		try {
			connection.close();
			statement.close();
			if (resultSet != null)
			resultSet.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	/**
	 * Converts an Arraylist<ArrayList<Object>> into a 2D array
	 * @param list the results of a query in the type of Arraylist<ArrayList<Object>>
	 * @return the results formatted as a 2D array
	 */
	private Object[][] arrayListTo2DArray(ArrayList<ArrayList<Object>> list) {
		Object[][] array = new Object[list.size()][];
		for (int i = 0; i < list.size(); i++) {
			ArrayList<Object> row = list.get(i);
			array[i] = row.toArray(new Object[row.size()]);
		}
		return array;
	}

	/**
	 * Executes a sql query
	 * @param sql the query string to be executed on the database
	 */
	protected void execute(String sql) {
		try {
			connect();
			statement.execute(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		finally {
			close();
		}
	}

	/**
	 * Executes a sql query and returns a DefaultTableModel
	 * @param sql the query string to be executed on the database
	 * @return the result set as a vector of vectors, a type of DefaultTableModel
	 */
	protected DefaultTableModel executeQueryToTable(String sql) {
		ArrayList<ArrayList<Object>> result = new ArrayList<ArrayList<Object>>();
		ArrayList<Object> columns = new ArrayList<Object>();
		connect();
		try {
			resultSet = statement.executeQuery(sql);
			int columnCount = resultSet.getMetaData().getColumnCount();
			for (int i = 1; i <= columnCount; i++)
			columns.add(resultSet.getMetaData().getColumnName(i));
			while (resultSet.next()) {
				ArrayList<Object> subresult = new ArrayList<Object>();
				for (int i = 1; i <= columnCount; i++)
				subresult.add(resultSet.getObject(i));
				result.add(subresult);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		close();
		return new DefaultTableModel(arrayListTo2DArray(result), columns.toArray());
	}

	/**
	 * Executes a SQL query
	 * @param sql the query string to be executed on the database
	 * @return the result set as an ArrayList<ArrayList<Object>>
	 */
	protected ArrayList<ArrayList<Object>> executeQuery(String sql) {
		ArrayList<ArrayList<Object>> result = new ArrayList<ArrayList<Object>>();
		connect();
		try {
			resultSet = statement.executeQuery(sql);
			int columnCount = resultSet.getMetaData().getColumnCount();
			while (resultSet.next()) {
				ArrayList<Object> subresult = new ArrayList<Object>();
				for (int i = 1; i <= columnCount; i++) {
					subresult.add(resultSet.getObject(i));
				}
				result.add(subresult);
			}
		} catch (SQLException e){
			e.printStackTrace();
		}
		close();
		return result;
	}

}