package DBHelper;

//Required imports
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;


/**
 * Helper class for the EngineeringStudents table
 * Inherits from DBHelper
 * Code generated by SQL Helper
 */
public class EngineeringStudents extends DBHelper {

	/**
	 * A static value for the name of the SQL table the code was generated for
	 */
	private final String TABLE_NAME = "EngineeringStudents";

	/**
	 * A static value for the Student ID column
	 */
	public static final String Student_ID = "Student_ID";

	/**
	 * A static value for the Department column
	 */
	public static final String Department = "Department";

	/**
	 * A static value for the First name column
	 */
	public static final String First_Name = "First_Name";

	/**
	 * A static value for the Last name column
	 */
	public static final String Last_Name = "Last_Name";

	/**
	 * A static value for the Pass Out Year column
	 */
	public static final String PassOutYear = "PassOutYear";

	/**
	 * A static value for the University Rank column
	 */
	public static final String UniversityRank = "UniversityRank";


	/**
	 * Prepares the text of a SQL "select" command and returns the query string.
	 * @param fields the fields to be displayed in the output
	 * @param whatField field to search for
	 * @param whatValue value to search for within whatField
	 * @param sortField the field that the data will be sorted by
	 * @param sort use ASC or DESC to specify the sorting order
	 * @return a string value representing a formatted SQL select query
	 */
	private String prepareSQL(String fields, String whatField, String whatValue, String sortField, String sort) {
		String query = "SELECT ";
		query += fields == null ? " * FROM " + TABLE_NAME : fields + " FROM " + TABLE_NAME;
		query += whatField != null && whatValue != null ? " WHERE " + whatField + " = \"" + whatValue + "\"" : "";
		query += sort != null && sortField != null ? " order by " + sortField + " " + sort : "";
		return query;
	}

	/**
	 * Inserts a new record into the database
	 * @param Student_ID the numeric ID for the student being inserted
	 * @param Department the Department name for the student being inserted
	 * @param First_Name the students first name
	 * @param Last_Name the students last name
	 * @param PassOutYear the numerical year the student ends the program
	 * @param UniversityRank the numerical ranking of the student
	 */
	public void insert(Integer Student_ID, String Department, String First_Name, String Last_Name, Integer PassOutYear, Integer UniversityRank) {
		Department = Department != null ? "\"" + Department + "\"" : null;
		First_Name = First_Name != null ? "\"" + First_Name + "\"" : null;
		Last_Name = Last_Name != null ? "\"" + Last_Name + "\"" : null;
		
		Object[] values_ar = {Student_ID, Department, First_Name, Last_Name, PassOutYear, UniversityRank};
		String[] fields_ar = {EngineeringStudents.Student_ID, EngineeringStudents.Department, EngineeringStudents.First_Name, EngineeringStudents.Last_Name, EngineeringStudents.PassOutYear, EngineeringStudents.UniversityRank};
		String values = "", fields = "";
		for (int i = 0; i < values_ar.length; i++) {
			if (values_ar[i] != null) {
				values += values_ar[i] + ", ";
				fields += fields_ar[i] + ", ";
			}
		}
		if (!values.isEmpty()) {
			values = values.substring(0, values.length() - 2);
			fields = fields.substring(0, fields.length() - 2);
			super.execute("INSERT INTO " + TABLE_NAME + "(" + fields + ") values(" + values + ");");
		}
	}

	/**
	 * Removes a record from the database
	 * @param whatField the field (key) used to determine if a row should be deleted
	 * @param whatValue the value of whatField that should be deleted
	 */
	public void delete(String whatField, String whatValue) {
		super.execute("DELETE from " + TABLE_NAME + " where " + whatField + " = " + whatValue + ";");
	}

	/**
	 * Updates a record in the database
	 * @param whatField the field that should be updated
	 * @param whatValue the value of whatField that should be updated
	 * @param whereField the field (key) used to determine if a row should be updated
	 * @param whereValue the value of whatField that should be updated
	 */
	public void update(String whatField, String whatValue, String whereField, String whereValue) {
		super.execute("UPDATE " + TABLE_NAME + " set " + whatField + " = \"" + whatValue + "\" where " + whereField + " = \"" + whereValue + "\";");
	}

	/**
	 * Returns an 2D array of objects from a SQL select command
	 * @param fields the fields to be displayed in the output
	 * @param whatField the field to search within
	 * @param whatValue the value to search for within the whatField
	 * @param sortField the field that the data will be sorted by
	 * @param sort use ASC or DESC to specify the sorting order
	 * @return a 2D array of objects, the results of the generated SQL select command
	 */
	public ArrayList<ArrayList<Object>> select(String fields, String whatField, String whatValue, String sortField, String sort) {
		return super.executeQuery(prepareSQL(fields, whatField, whatValue, sortField, sort));
	}

	/**
	 * Performs a search of the database where the query is a SQL Command that would be entered on the command line
	 * @param query the SQL command that would be entered at the command line
	 * @return a 2D array of objects that are a result of the run query.
	 */
	public ArrayList<ArrayList<Object>> getExecuteResult(String query) {
		return super.executeQuery(query);
	}

	/**
	 * Performs a SQL command, where the String query is the SQL command that would be entered on the command line
	 * @param query the SQL command that would be entered at the command line
	 */
	public void execute(String query) {
		super.execute(query);
	}

	/**
	 * Performs a search of the database from a SQL select command
	 * @param fields the fields to be displayed in the output
	 * @param whatField the field to search within
	 * @param whatValue the value to search for within the whatField
	 * @param sortField the field that the data will be sorted by
	 * @param sort use ASC or DESC to specify the sorting order
	 * @return a DefaultTableModel, a vector of vectors, to store data
	 */
	public DefaultTableModel selectToTable(String fields, String whatField, String whatValue, String sortField, String sort) {
		return super.executeQueryToTable(prepareSQL(fields, whatField, whatValue, sortField, sort));
	}

}